
# ----------------------
#    Site settings
# ----------------------

# title: Kevando
description: Chaz
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chaz.co" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed


# ----------------------
#      SEO Shit
# ----------------------

google_analytics: UA-89282611-1


# ----------------------
#    Groups of Shit
# ----------------------

collections:
  moments:
    output: true

defaults:
  -
    scope:
      path: ""
      type: moment
    values:
      layout: "moment"
