
# Site settings
title: Moments of Empathy
description: It's nice to be your neighbor.
baseurl: "/" 
url: "https://chaz.co" 

# SEO
google_analytics: UA-89282611-1

# CMS
collections:
  moments:
    output: true
    sort_by: sort

defaults:
  -
    scope:
      path: ""
      type: moment
    values:
      layout: "moment"



# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
