# Basic 
title: Chaz
description: It's nice to be your neighbor.
baseurl: "/" 
url: "https://chaz.co" 

# Images
icon16: /assets/favicon/favicon-16x16.png
icon32: /assets/favicon/favicon-32x32.png
icon256: /assets/favicon/apple-touch-icon-256.png

# SEO
google_analytics: UA-89282611-1


# ----------------------------
#       Collections
# ----------------------------

collections_dir: collections

defaults:
  -
    scope:
      path: "" # all files
      type: pages
    values:
      layout: "basic"
      description: For chazzy people.
      twitter_title: Moments of Empathy
      twitter_description: A collection of people demonstrating deep understanding 
      twitter_image: https://chaz.co/assets/images/skinner.png
      facebook_title: Moments of Empathy
      facebook_description:
      facebook_image: https://chaz.co/assets/images/skinner.png


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed


