title: Chaz
description: It's nice to be your neighbor.
baseurl: "/" 
url: "https://chaz.co" 

# Icons
icon16: /assets/favicon/favicon-16x16.png
icon32: /assets/favicon/favicon-32x32.png
icon256: /assets/favicon/apple-touch-icon-256.png

shared_assets_url: https://kevando.github.io/assets

google_analytics: UA-89282611-1

email: khabich@gmail.com
twitter_handle: kevando_

# Meta Tags
twitter_card_style: summary_large_image

collections_dir: collections
collections:
  moments:
    output: false

defaults:
  -
    scope:
      path: "" # all files
      type: pages
    values:
      layout: "basic"
      twitter:
        title: Moments of Empathy
      facebook:
        title: Moments of Empathy
      


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed


