
# Site Settings
title: Moments of Empathy
description: It's nice to be your neighbor.
baseurl: "/" 
url: "https://chaz.co" 

# SEO
google_analytics: UA-89282611-1

# CMS
collections:
  moments:
    output: true

defaults:
  -
    scope:
      path: "" # all files
      type: pages
    values:
      layout: "moment"
      description: For chazzy people.
      twitter_title: Moments of Empathy
      twitter_description: A collection of people demonstrating deep understanding 
      twitter_image: https://chaz.co/assets/images/skinner.png
      facebook_title: Moments of Great Empathy
      facebook_description:
      facebook_image: https://chaz.co/assets/images/skinner.png


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed


